import {useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowDown,ArrowUpRight,Radio,ShieldCheck,ScanLine,Route} from 'lucide-react';
import {Button} from '../../components/common/Button';
import {SectionHeading} from '../../components/common/SectionHeading';
import {Reveal} from '../../components/common/Reveal';
import {services} from '../../data/services';
import {fleet} from '../../data/fleet';
import {coverage} from '../../data/coverage';
import {media} from '../../config/media';
import {FilmMedia} from '../../components/common/FilmMedia';
import {CinematicHero} from '../../components/common/CinematicHero';
import {ServiceMotion} from '../../components/common/ServiceMotion';
import {OperationsPulse} from '../../components/common/OperationsPulse';
import {NetworkMap} from '../../components/common/NetworkMap';
export function Hero(){return <section className="hero" id="top"><div className="hero-visual"><CinematicHero/><div className="hero-visual-shade"/></div><div className="hero-content container"><div className="hero-copy"><p className="eyebrow">FINAL-MILE DELIVERY <span className="eyebrow-divider">/</span> CANADA</p><h1>From warehouse.<br/><em>To doorstep.</em></h1><p className="hero-description">Same-day final-mile delivery powered by a flexible fleet and active operations.</p><div className="hero-buttons"><Button to="/quote">Get a Quote</Button><Button to="/coverage" variant="outline">Explore Our Network</Button></div></div></div><div className="hero-bottom container"><span>VELCOTIY <span className="hero-separator">—</span> WAREHOUSE TO DOORSTEP</span><a href="#journey" className="scroll-cue">EXPLORE <ArrowDown size={15}/></a></div></section>}
export function Journey(){return <section className="section journey" id="journey"><div className="container"><Reveal><div className="journey-intro"><p className="eyebrow">THE DELIVERY JOURNEY</p><h2>From first scan<br/><em>to final handoff.</em></h2><p>People, vehicles and operations connected across every stage.</p></div></Reveal></div><div className="film-frame"><FilmMedia/><div className="film-overlay"><span>01 / THE JOURNEY</span><span>WAREHOUSE → DOORSTEP</span></div><div className="film-bottom"><h3><br/></h3></div></div><div className="container"><div className="journey-steps">{['WAREHOUSE','SORT','LOAD','DISPATCH','DELIVER'].map((item,i)=><div key={item}><span>0{i+1}</span><p>{item}</p></div>)}</div></div></section>}
export function TorontoFinalMile(){return <section className="toronto-story" aria-labelledby="toronto-story-title"><div className="toronto-story-photo"><img src={media.city.torontoDelivery} alt="Final-mile delivery van on a Toronto street with the city skyline in the background." width="1672" height="941" loading="lazy"/></div><div className="container toronto-story-content"><p className="eyebrow">WAREHOUSE TO DOORSTEP</p><h2 id="toronto-story-title">Final mile,<br/><em>handled end to end.</em></h2><p>Velcotiy manages the final leg from warehouse dispatch to customer delivery, with drivers, fleet coordination and active operational oversight.</p><Button to="/services" variant="outline">How We Deliver</Button></div></section>}
export function FleetPreview(){const [selected,setSelected]=useState(0);const vehicle=fleet[selected];return <section className="section fleet-section"><div className="container"><Reveal><div className="section-top"><SectionHeading eyebrow="BUILT FOR THE ROUTE" title={<>One fleet.<br/><em>Every delivery requirement.</em></>} copy="Vehicle choice follows the route, parcel volume and business need."/><Button to="/fleet" variant="text">Explore the fleet</Button></div></Reveal><div className="fleet-editorial"><div className="fleet-editorial-image"><img key={vehicle.image} src={vehicle.image} srcSet={`${vehicle.imageSmall} 768w, ${vehicle.image} 1536w`} sizes="(max-width: 640px) 100vw, (max-width: 1024px) 90vw, 65vw" alt={`${vehicle.name} Velcotiy delivery vehicle`} width="1536" height="1024" loading="eager" decoding="async"/></div><div className="fleet-editorial-panel"><div className="fleet-selector" role="group" aria-label="Choose a fleet category">{fleet.map((item,i)=><button key={item.name} className={i===selected?'active':''} aria-pressed={i===selected} onClick={()=>setSelected(i)}><span>{String(i+1).padStart(2,'0')}</span>{item.name}<ArrowUpRight size={16}/></button>)}</div><div className="fleet-selected" aria-live="polite"><span>{vehicle.category.toUpperCase()} / {vehicle.power.toUpperCase()}</span><h3>{vehicle.name}</h3><p>{vehicle.description}</p><small>BEST FOR · {vehicle.use.toUpperCase()}</small></div></div></div></div></section>}
export function Stats(){const capabilities=[['Same-Day','Delivery options'],['Mixed Fleet','Route flexibility'],['Active','Operations oversight'],['Final Mile','Warehouse to doorstep']];return <section className="stats-section"><div className="container"><p className="eyebrow"><span className="eyebrow-dot"/>HOW WE DELIVER</p><div className="stats-grid">{capabilities.map(([value,label],i)=><div className="stat stat--text" key={label}><span>0{i+1}</span><strong>{value}</strong><p>{label}</p></div>)}</div></div></section>}
export function Operations(){const labels=['Fleet Status','Route Progress','Parcel Status','Driver Communication'];return <section className="section operations"><img className="operations-background" src={media.operations.center} alt="" loading="lazy" width="1774" height="887"/><div className="container operations-grid"><Reveal><div className="operations-copy"><SectionHeading eyebrow="OPERATIONAL OVERSIGHT" title={<>Every delivery.<br/><em>Monitored from pickup to completion.</em></>} copy="A connected operational view helps teams coordinate drivers, follow route progress and respond when plans change."/><div className="feature-list"><p><Radio/> Driver coordination</p><p><Route/> Route oversight</p><p><ShieldCheck/> Delivery verification</p><p><ScanLine/> Parcel security</p></div></div></Reveal><Reveal><div className="dashboard"><div className="dashboard-header"><span><i/> VELCOTIY / OPERATIONS</span><OperationsPulse/></div><div className="dashboard-main"><div className="dashboard-map"><div className="dashboard-route route-a"/><div className="dashboard-route route-b"/><span className="dash-pin pin-a"/><span className="dash-pin pin-b"/><span className="dash-pin pin-c"/><span className="dash-pin pin-d"/><div className="dashboard-map-label">NETWORK OVERVIEW <span>↗</span></div></div><div className="dashboard-panel"><div className="dashboard-panel-title">ROUTE PROGRESS <span>•••</span></div>{['Warehouse scan','Driver assigned','In transit','Delivery confirmation'].map((item,i)=><div className="dash-progress" key={item}><span className={i<3?'complete':''}>{i<3?'✓':i+1}</span><div>{item}<small>{i<3?'Stage represented':'Next stage'}</small></div></div>)}</div></div><div className="dashboard-footer">{labels.map((label,i)=><div key={label}><span>0{i+1}</span><p>{label}</p><i/></div>)}</div></div></Reveal></div></section>}
export function ServicesPreview(){return <section className="section services-preview"><div className="container"><Reveal><div className="section-top"><SectionHeading eyebrow="WHAT WE DO" title={<>Delivery solutions,<br/><em>built around you.</em></>} copy="One operating partner for a range of final-mile requirements."/><Button to="/services" variant="text">All services</Button></div></Reveal><div className="service-grid">{services.slice(0,4).map(service=><Link to={`/services#${service.id}`} className="service-card" key={service.id}><span className="service-index">{service.index}</span><div><h3>{service.title}</h3><p>{service.description}</p></div><ServiceMotion id={service.id}/><ArrowUpRight size={20}/></Link>)}</div></div></section>}
export function Sustainability(){return <section className="section sustainability"><div className="container sustainability-grid"><Reveal><div><p className="eyebrow lime">EV-FORWARD THINKING</p><h2>Built for today's routes.<br/><em>Moving toward a cleaner fleet.</em></h2><p className="section-copy">We are expanding EV use where it suits the route, while keeping delivery capacity flexible.</p><Button to="/fleet" variant="outline">Meet the fleet</Button></div></Reveal><div className="ev-visual"><img src={media.ev.delivery} alt="Velcotiy electric delivery vehicle" width="1536" height="1024" loading="lazy" decoding="async"/><div className="ev-energy-line"/><div className="ev-technical">EV DELIVERY <span>VELCOTIY / ELECTRIC DELIVERY</span></div></div></div></section>}
export function CoveragePreview(){return <section className="section coverage-preview"><div className="container"><Reveal><div className="section-top"><SectionHeading eyebrow="SERVICE INQUIRIES" title={<>Plan for your<br/><em>delivery market.</em></>} copy="Final-mile operations planned around business needs, route fit and available capacity. Ask us about your market."/><Button to="/coverage" variant="text">Explore coverage</Button></div></Reveal><div className="near-network"><NetworkMap/></div><div className="coverage-city-list" aria-label="Markets available for inquiry">{coverage.map(location=><span key={location.city}>{location.city}</span>)}</div><p className="data-note">Listed markets are examples for inquiries; confirm current service availability with our team.</p></div></section>}
export function AboutPreview(){return <section className="section about-preview"><div className="container about-preview-grid"><Reveal><div><p className="eyebrow">WHO WE ARE</p><h2>Logistics is infrastructure.<br/><em>We make it move.</em></h2><p className="section-copy">Velcotiy Techniques Inc is a Canadian final-mile delivery and delivery operations business. We coordinate drivers, flexible fleet capacity and delivery oversight from warehouse to doorstep.</p><Button to="/about" variant="text">Our Story</Button></div></Reveal><div className="about-visual"><img src={media.operations.center} alt="Dispatch team coordinating delivery routes" width="1774" height="887" loading="lazy"/><span>OPERATIONS / PEOPLE / PROGRESS</span></div></div></section>}
